name: Deploy Node.js App

on:
  push:
    branches:
      - main  # Deploy on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 18.217.97.15
          username: root  # Change if using a different user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /node-app/node-app
            git pull origin main
            npm install
            pm2 restart node-app

